[tasks.clippy]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.fmt]
workspace = false
command = "cargo"
toolchain = "nightly"
args = [
	"fmt",
	"--all",
]

[tasks.nextest]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.udeps]
workspace = false
command = "cargo"
toolchain = "nightly"
args = [
	"udeps",
	"--workspace",
	"--all-targets",
	"--all-features",
]

# Examples

[tasks.example-client-credentials]
workspace = false
command = "cargo"
args = [
	"run",
	"--example",
	"client_credentials",
]

[tasks.example-custom-transport]
workspace = false
command = "cargo"
args = [
	"run",
	"--example",
	"custom_transport",
]

[tasks.example-start-authorization]
workspace = false
command = "cargo"
args = [
	"run",
	"--example",
	"start_authorization",
]

[tasks.example-x-authorization]
workspace = false
command = "cargo"
args = [
	"run",
	"--example",
	"x_authorization",
]

[tasks.examples]
dependencies = [
	"example-client-credentials",
	"example-custom-transport",
	"example-start-authorization",
]
